name: Auto-merge Dependabot

on: pull_request

jobs:
  automerge:
    name: Check and merge PR
    if: github.actor == 'dependabot[bot]'

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Fetch metadata
        uses: dependabot/fetch-metadata@v2
        id: metadata
        with:
          github-token: ${{ github.token }}

      - name: Enable auto-merge
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr merge --auto --squash "$PR"
        env:
          GH_TOKEN: ${{ github.token }}
          PR: ${{ github.event.pull_request.html_url }}
