name: Auto-merge Dependabot

on: pull_request

jobs:
  automerge:
    name: Check and merge PR
    if: github.actor == 'dependabot[bot]'

    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Fetch metadata
        uses: dependabot/fetch-metadata@v2
        id: metadata
        with:
          github-token: ${{ steps.app-token.outputs.token }}

      - name: Enable auto-merge
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor' }}
        run: gh pr merge --auto --squash "$PR"
        env:
          PR: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
